[package]
name = "museum"
version = "0.4.2"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31.0", features = ["bundled"] }
color-eyre = "0.6.3"

# Not sure yet…
## Will use later when more args are required.
clap = { version = "4.5.3", features = ["derive"] }
clap_complete = "4.5.1"
# Colors in output. Use when there’s more output.
nu-ansi-term = "0.49"
