[package]
name = "museum"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.31.0", features = ["bundled"] }
normpath = "1.2"

# Not sure yet…
## To many error types.
anyhow = "1.0.81"
## Will use later when more args are required.
clap = { version = "4.5.3", features = ["derive"] }
clap_complete = "4.5.1"
# Alternative to `fs::canonicalize`.
# Colors in output. Use when there’s more output.
nu-ansi-term = "0.49"
